---
- name: Install iptables management utilities.
  package:
    name: "{{ item }}"
    state: present
  loop:
    - iptables
    - iptables-persistent

- name: Configure iptables firewall.
  register: configure_iptables
  template:
    src: "iptables.rules.j2"
    dest: "/etc/iptables/rules.v{{ item.version }}"
    validate: "iptables-restore --test %s"
  loop:
    - version: 4
      ip_tables: "{{ ipv4_tables | default({}) }}"
    - version: 6
      ip_tables: "{{ ipv6_tables | default({}) }}"
  notify: Apply iptables rules.

- name: Apply firewall configuration.
  when: configure_iptables is changed
  meta: flush_handlers
